// <auto-generated>
// Code generated by build/SharpDnp3.Generator from
// src/SharpDnp3/Objects/Spec/dnp3_objects.yaml. DO NOT EDIT.
// </auto-generated>
//
// SharpDnp3 — a DNP3 (IEEE 1815-2012) implementation in C#.
// Copyright (C) 2026 Ricardo Olsen / DSC Systems
// Licensed under the GNU General Public License v3.0 or later.

namespace SharpDnp3.Objects;

public static partial class ObjectRegistry
{
    /// <summary>Every group and variation the spec defines.</summary>
    private static readonly Dictionary<GroupVar, Descriptor> Descriptors = new()
    {
        [GroupVar.GV(1, 1)] = new Descriptor
        {
            GV = GroupVar.GV(1, 1),
            Name = "BinaryInputPacked",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.Binary,
            SizeBits = 1,
            Packed = true,
        },
        [GroupVar.GV(1, 2)] = new Descriptor
        {
            GV = GroupVar.GV(1, 2),
            Name = "BinaryInputWithFlags",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.Binary,
            SizeBits = 8,
            HasFlags = true,
        },
        [GroupVar.GV(2, 1)] = new Descriptor
        {
            GV = GroupVar.GV(2, 1),
            Name = "BinaryInputEventNoTime",
            Level = 1,
            Kind = Kind.Event,
            Measurement = PointType.Binary,
            SizeBits = 8,
            HasFlags = true,
        },
        [GroupVar.GV(2, 2)] = new Descriptor
        {
            GV = GroupVar.GV(2, 2),
            Name = "BinaryInputEventAbsTime",
            Level = 1,
            Kind = Kind.Event,
            Measurement = PointType.Binary,
            SizeBits = 56,
            HasFlags = true,
            HasTime = true,
        },
        [GroupVar.GV(2, 3)] = new Descriptor
        {
            GV = GroupVar.GV(2, 3),
            Name = "BinaryInputEventRelTime",
            Level = 1,
            Kind = Kind.Event,
            Measurement = PointType.Binary,
            SizeBits = 24,
            HasFlags = true,
            HasTime = true,
            RelativeTime = true,
        },
        [GroupVar.GV(3, 1)] = new Descriptor
        {
            GV = GroupVar.GV(3, 1),
            Name = "DoubleBitInputPacked",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.DoubleBitBinary,
            SizeBits = 2,
            Packed = true,
        },
        [GroupVar.GV(3, 2)] = new Descriptor
        {
            GV = GroupVar.GV(3, 2),
            Name = "DoubleBitInputWithFlags",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.DoubleBitBinary,
            SizeBits = 8,
            HasFlags = true,
        },
        [GroupVar.GV(4, 1)] = new Descriptor
        {
            GV = GroupVar.GV(4, 1),
            Name = "DoubleBitEventNoTime",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.DoubleBitBinary,
            SizeBits = 8,
            HasFlags = true,
        },
        [GroupVar.GV(4, 2)] = new Descriptor
        {
            GV = GroupVar.GV(4, 2),
            Name = "DoubleBitEventAbsTime",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.DoubleBitBinary,
            SizeBits = 56,
            HasFlags = true,
            HasTime = true,
        },
        [GroupVar.GV(4, 3)] = new Descriptor
        {
            GV = GroupVar.GV(4, 3),
            Name = "DoubleBitEventRelTime",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.DoubleBitBinary,
            SizeBits = 24,
            HasFlags = true,
            HasTime = true,
            RelativeTime = true,
        },
        [GroupVar.GV(10, 1)] = new Descriptor
        {
            GV = GroupVar.GV(10, 1),
            Name = "BinaryOutputPacked",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.BinaryOutputStatus,
            SizeBits = 1,
            Packed = true,
        },
        [GroupVar.GV(10, 2)] = new Descriptor
        {
            GV = GroupVar.GV(10, 2),
            Name = "BinaryOutputWithFlags",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.BinaryOutputStatus,
            SizeBits = 8,
            HasFlags = true,
        },
        [GroupVar.GV(11, 1)] = new Descriptor
        {
            GV = GroupVar.GV(11, 1),
            Name = "BinaryOutputEventNoTime",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.BinaryOutputStatus,
            SizeBits = 8,
            HasFlags = true,
        },
        [GroupVar.GV(11, 2)] = new Descriptor
        {
            GV = GroupVar.GV(11, 2),
            Name = "BinaryOutputEventAbsTime",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.BinaryOutputStatus,
            SizeBits = 56,
            HasFlags = true,
            HasTime = true,
        },
        [GroupVar.GV(12, 1)] = new Descriptor
        {
            GV = GroupVar.GV(12, 1),
            Name = "ControlRelayOutputBlock",
            Level = 1,
            Kind = Kind.Command,
            Measurement = PointType.Unknown,
            SizeBits = 88,
        },
        [GroupVar.GV(12, 2)] = new Descriptor
        {
            GV = GroupVar.GV(12, 2),
            Name = "PatternControlBlock",
            Level = 4,
            Kind = Kind.Command,
            Measurement = PointType.Unknown,
            SizeBits = 88,
        },
        [GroupVar.GV(12, 3)] = new Descriptor
        {
            GV = GroupVar.GV(12, 3),
            Name = "PatternMask",
            Level = 4,
            Kind = Kind.Command,
            Measurement = PointType.Unknown,
            SizeBits = 1,
            Packed = true,
        },
        [GroupVar.GV(13, 1)] = new Descriptor
        {
            GV = GroupVar.GV(13, 1),
            Name = "BinaryOutputCmdEventNoTime",
            Level = 4,
            Kind = Kind.CommandEvent,
            Measurement = PointType.Unknown,
            SizeBits = 8,
        },
        [GroupVar.GV(13, 2)] = new Descriptor
        {
            GV = GroupVar.GV(13, 2),
            Name = "BinaryOutputCmdEventAbsTime",
            Level = 4,
            Kind = Kind.CommandEvent,
            Measurement = PointType.Unknown,
            SizeBits = 56,
            HasTime = true,
        },
        [GroupVar.GV(20, 1)] = new Descriptor
        {
            GV = GroupVar.GV(20, 1),
            Name = "Counter32WithFlag",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.Counter,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
        },
        [GroupVar.GV(20, 2)] = new Descriptor
        {
            GV = GroupVar.GV(20, 2),
            Name = "Counter16WithFlag",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.Counter,
            SizeBits = 24,
            HasFlags = true,
            ValueBits = 16,
        },
        [GroupVar.GV(20, 5)] = new Descriptor
        {
            GV = GroupVar.GV(20, 5),
            Name = "Counter32NoFlag",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.Counter,
            SizeBits = 32,
            ValueBits = 32,
        },
        [GroupVar.GV(20, 6)] = new Descriptor
        {
            GV = GroupVar.GV(20, 6),
            Name = "Counter16NoFlag",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.Counter,
            SizeBits = 16,
            ValueBits = 16,
        },
        [GroupVar.GV(21, 1)] = new Descriptor
        {
            GV = GroupVar.GV(21, 1),
            Name = "FrozenCounter32WithFlag",
            Level = 2,
            Kind = Kind.Static,
            Measurement = PointType.FrozenCounter,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
        },
        [GroupVar.GV(21, 2)] = new Descriptor
        {
            GV = GroupVar.GV(21, 2),
            Name = "FrozenCounter16WithFlag",
            Level = 2,
            Kind = Kind.Static,
            Measurement = PointType.FrozenCounter,
            SizeBits = 24,
            HasFlags = true,
            ValueBits = 16,
        },
        [GroupVar.GV(21, 5)] = new Descriptor
        {
            GV = GroupVar.GV(21, 5),
            Name = "FrozenCounter32WithFlagTime",
            Level = 2,
            Kind = Kind.Static,
            Measurement = PointType.FrozenCounter,
            SizeBits = 88,
            HasFlags = true,
            HasTime = true,
            ValueBits = 32,
        },
        [GroupVar.GV(21, 6)] = new Descriptor
        {
            GV = GroupVar.GV(21, 6),
            Name = "FrozenCounter16WithFlagTime",
            Level = 2,
            Kind = Kind.Static,
            Measurement = PointType.FrozenCounter,
            SizeBits = 72,
            HasFlags = true,
            HasTime = true,
            ValueBits = 16,
        },
        [GroupVar.GV(21, 9)] = new Descriptor
        {
            GV = GroupVar.GV(21, 9),
            Name = "FrozenCounter32NoFlag",
            Level = 2,
            Kind = Kind.Static,
            Measurement = PointType.FrozenCounter,
            SizeBits = 32,
            ValueBits = 32,
        },
        [GroupVar.GV(21, 10)] = new Descriptor
        {
            GV = GroupVar.GV(21, 10),
            Name = "FrozenCounter16NoFlag",
            Level = 2,
            Kind = Kind.Static,
            Measurement = PointType.FrozenCounter,
            SizeBits = 16,
            ValueBits = 16,
        },
        [GroupVar.GV(22, 1)] = new Descriptor
        {
            GV = GroupVar.GV(22, 1),
            Name = "CounterEvent32WithFlag",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.Counter,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
        },
        [GroupVar.GV(22, 2)] = new Descriptor
        {
            GV = GroupVar.GV(22, 2),
            Name = "CounterEvent16WithFlag",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.Counter,
            SizeBits = 24,
            HasFlags = true,
            ValueBits = 16,
        },
        [GroupVar.GV(22, 5)] = new Descriptor
        {
            GV = GroupVar.GV(22, 5),
            Name = "CounterEvent32WithFlagTime",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.Counter,
            SizeBits = 88,
            HasFlags = true,
            HasTime = true,
            ValueBits = 32,
        },
        [GroupVar.GV(22, 6)] = new Descriptor
        {
            GV = GroupVar.GV(22, 6),
            Name = "CounterEvent16WithFlagTime",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.Counter,
            SizeBits = 72,
            HasFlags = true,
            HasTime = true,
            ValueBits = 16,
        },
        [GroupVar.GV(23, 1)] = new Descriptor
        {
            GV = GroupVar.GV(23, 1),
            Name = "FrozenCounterEvent32WithFlag",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.FrozenCounter,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
        },
        [GroupVar.GV(23, 2)] = new Descriptor
        {
            GV = GroupVar.GV(23, 2),
            Name = "FrozenCounterEvent16WithFlag",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.FrozenCounter,
            SizeBits = 24,
            HasFlags = true,
            ValueBits = 16,
        },
        [GroupVar.GV(23, 5)] = new Descriptor
        {
            GV = GroupVar.GV(23, 5),
            Name = "FrozenCounterEvent32WithFlagTime",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.FrozenCounter,
            SizeBits = 88,
            HasFlags = true,
            HasTime = true,
            ValueBits = 32,
        },
        [GroupVar.GV(23, 6)] = new Descriptor
        {
            GV = GroupVar.GV(23, 6),
            Name = "FrozenCounterEvent16WithFlagTime",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.FrozenCounter,
            SizeBits = 72,
            HasFlags = true,
            HasTime = true,
            ValueBits = 16,
        },
        [GroupVar.GV(30, 1)] = new Descriptor
        {
            GV = GroupVar.GV(30, 1),
            Name = "AnalogInput32WithFlag",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
        },
        [GroupVar.GV(30, 2)] = new Descriptor
        {
            GV = GroupVar.GV(30, 2),
            Name = "AnalogInput16WithFlag",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 24,
            HasFlags = true,
            ValueBits = 16,
        },
        [GroupVar.GV(30, 3)] = new Descriptor
        {
            GV = GroupVar.GV(30, 3),
            Name = "AnalogInput32NoFlag",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 32,
            ValueBits = 32,
        },
        [GroupVar.GV(30, 4)] = new Descriptor
        {
            GV = GroupVar.GV(30, 4),
            Name = "AnalogInput16NoFlag",
            Level = 1,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 16,
            ValueBits = 16,
        },
        [GroupVar.GV(30, 5)] = new Descriptor
        {
            GV = GroupVar.GV(30, 5),
            Name = "AnalogInputFloatWithFlag",
            Level = 2,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(30, 6)] = new Descriptor
        {
            GV = GroupVar.GV(30, 6),
            Name = "AnalogInputDoubleWithFlag",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 72,
            HasFlags = true,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(31, 1)] = new Descriptor
        {
            GV = GroupVar.GV(31, 1),
            Name = "FrozenAnalog32WithFlag",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
        },
        [GroupVar.GV(31, 2)] = new Descriptor
        {
            GV = GroupVar.GV(31, 2),
            Name = "FrozenAnalog16WithFlag",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 24,
            HasFlags = true,
            ValueBits = 16,
        },
        [GroupVar.GV(31, 3)] = new Descriptor
        {
            GV = GroupVar.GV(31, 3),
            Name = "FrozenAnalog32WithFlagTime",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 88,
            HasFlags = true,
            HasTime = true,
            ValueBits = 32,
        },
        [GroupVar.GV(31, 4)] = new Descriptor
        {
            GV = GroupVar.GV(31, 4),
            Name = "FrozenAnalog16WithFlagTime",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 72,
            HasFlags = true,
            HasTime = true,
            ValueBits = 16,
        },
        [GroupVar.GV(31, 5)] = new Descriptor
        {
            GV = GroupVar.GV(31, 5),
            Name = "FrozenAnalog32NoFlag",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 32,
            ValueBits = 32,
        },
        [GroupVar.GV(31, 6)] = new Descriptor
        {
            GV = GroupVar.GV(31, 6),
            Name = "FrozenAnalog16NoFlag",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 16,
            ValueBits = 16,
        },
        [GroupVar.GV(31, 7)] = new Descriptor
        {
            GV = GroupVar.GV(31, 7),
            Name = "FrozenAnalogFloatWithFlag",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(31, 8)] = new Descriptor
        {
            GV = GroupVar.GV(31, 8),
            Name = "FrozenAnalogDoubleWithFlag",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.Analog,
            SizeBits = 72,
            HasFlags = true,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(32, 1)] = new Descriptor
        {
            GV = GroupVar.GV(32, 1),
            Name = "AnalogEvent32WithFlag",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
        },
        [GroupVar.GV(32, 2)] = new Descriptor
        {
            GV = GroupVar.GV(32, 2),
            Name = "AnalogEvent16WithFlag",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 24,
            HasFlags = true,
            ValueBits = 16,
        },
        [GroupVar.GV(32, 3)] = new Descriptor
        {
            GV = GroupVar.GV(32, 3),
            Name = "AnalogEvent32WithFlagTime",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 88,
            HasFlags = true,
            HasTime = true,
            ValueBits = 32,
        },
        [GroupVar.GV(32, 4)] = new Descriptor
        {
            GV = GroupVar.GV(32, 4),
            Name = "AnalogEvent16WithFlagTime",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 72,
            HasFlags = true,
            HasTime = true,
            ValueBits = 16,
        },
        [GroupVar.GV(32, 5)] = new Descriptor
        {
            GV = GroupVar.GV(32, 5),
            Name = "AnalogEventFloatWithFlag",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(32, 6)] = new Descriptor
        {
            GV = GroupVar.GV(32, 6),
            Name = "AnalogEventDoubleWithFlag",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 72,
            HasFlags = true,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(32, 7)] = new Descriptor
        {
            GV = GroupVar.GV(32, 7),
            Name = "AnalogEventFloatWithFlagTime",
            Level = 2,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 88,
            HasFlags = true,
            HasTime = true,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(32, 8)] = new Descriptor
        {
            GV = GroupVar.GV(32, 8),
            Name = "AnalogEventDoubleWithFlagTime",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 120,
            HasFlags = true,
            HasTime = true,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(33, 1)] = new Descriptor
        {
            GV = GroupVar.GV(33, 1),
            Name = "FrozenAnalogEvent32WithFlag",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
        },
        [GroupVar.GV(33, 2)] = new Descriptor
        {
            GV = GroupVar.GV(33, 2),
            Name = "FrozenAnalogEvent16WithFlag",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 24,
            HasFlags = true,
            ValueBits = 16,
        },
        [GroupVar.GV(33, 3)] = new Descriptor
        {
            GV = GroupVar.GV(33, 3),
            Name = "FrozenAnalogEvent32WithFlagTime",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 88,
            HasFlags = true,
            HasTime = true,
            ValueBits = 32,
        },
        [GroupVar.GV(33, 4)] = new Descriptor
        {
            GV = GroupVar.GV(33, 4),
            Name = "FrozenAnalogEvent16WithFlagTime",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 72,
            HasFlags = true,
            HasTime = true,
            ValueBits = 16,
        },
        [GroupVar.GV(33, 5)] = new Descriptor
        {
            GV = GroupVar.GV(33, 5),
            Name = "FrozenAnalogEventFloatWithFlag",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(33, 6)] = new Descriptor
        {
            GV = GroupVar.GV(33, 6),
            Name = "FrozenAnalogEventDoubleWithFlag",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 72,
            HasFlags = true,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(33, 7)] = new Descriptor
        {
            GV = GroupVar.GV(33, 7),
            Name = "FrozenAnalogEventFloatWithFlagTime",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 88,
            HasFlags = true,
            HasTime = true,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(33, 8)] = new Descriptor
        {
            GV = GroupVar.GV(33, 8),
            Name = "FrozenAnalogEventDoubleWithFlagTime",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.Analog,
            SizeBits = 120,
            HasFlags = true,
            HasTime = true,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(34, 1)] = new Descriptor
        {
            GV = GroupVar.GV(34, 1),
            Name = "AnalogDeadband16",
            Level = 4,
            Kind = Kind.Deadband,
            Measurement = PointType.Unknown,
            SizeBits = 16,
            ValueBits = 16,
        },
        [GroupVar.GV(34, 2)] = new Descriptor
        {
            GV = GroupVar.GV(34, 2),
            Name = "AnalogDeadband32",
            Level = 4,
            Kind = Kind.Deadband,
            Measurement = PointType.Unknown,
            SizeBits = 32,
            ValueBits = 32,
        },
        [GroupVar.GV(34, 3)] = new Descriptor
        {
            GV = GroupVar.GV(34, 3),
            Name = "AnalogDeadbandFloat",
            Level = 4,
            Kind = Kind.Deadband,
            Measurement = PointType.Unknown,
            SizeBits = 32,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(40, 1)] = new Descriptor
        {
            GV = GroupVar.GV(40, 1),
            Name = "AnalogOutputStatus32",
            Level = 2,
            Kind = Kind.Static,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
        },
        [GroupVar.GV(40, 2)] = new Descriptor
        {
            GV = GroupVar.GV(40, 2),
            Name = "AnalogOutputStatus16",
            Level = 2,
            Kind = Kind.Static,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 24,
            HasFlags = true,
            ValueBits = 16,
        },
        [GroupVar.GV(40, 3)] = new Descriptor
        {
            GV = GroupVar.GV(40, 3),
            Name = "AnalogOutputStatusFloat",
            Level = 2,
            Kind = Kind.Static,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(40, 4)] = new Descriptor
        {
            GV = GroupVar.GV(40, 4),
            Name = "AnalogOutputStatusDouble",
            Level = 4,
            Kind = Kind.Static,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 72,
            HasFlags = true,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(41, 1)] = new Descriptor
        {
            GV = GroupVar.GV(41, 1),
            Name = "AnalogOutput32",
            Level = 2,
            Kind = Kind.Command,
            Measurement = PointType.Unknown,
            SizeBits = 40,
            ValueBits = 32,
        },
        [GroupVar.GV(41, 2)] = new Descriptor
        {
            GV = GroupVar.GV(41, 2),
            Name = "AnalogOutput16",
            Level = 2,
            Kind = Kind.Command,
            Measurement = PointType.Unknown,
            SizeBits = 24,
            ValueBits = 16,
        },
        [GroupVar.GV(41, 3)] = new Descriptor
        {
            GV = GroupVar.GV(41, 3),
            Name = "AnalogOutputFloat",
            Level = 2,
            Kind = Kind.Command,
            Measurement = PointType.Unknown,
            SizeBits = 40,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(41, 4)] = new Descriptor
        {
            GV = GroupVar.GV(41, 4),
            Name = "AnalogOutputDouble",
            Level = 4,
            Kind = Kind.Command,
            Measurement = PointType.Unknown,
            SizeBits = 72,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(42, 1)] = new Descriptor
        {
            GV = GroupVar.GV(42, 1),
            Name = "AnalogOutputEvent32",
            Level = 3,
            Kind = Kind.Event,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
        },
        [GroupVar.GV(42, 2)] = new Descriptor
        {
            GV = GroupVar.GV(42, 2),
            Name = "AnalogOutputEvent16",
            Level = 3,
            Kind = Kind.Event,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 24,
            HasFlags = true,
            ValueBits = 16,
        },
        [GroupVar.GV(42, 3)] = new Descriptor
        {
            GV = GroupVar.GV(42, 3),
            Name = "AnalogOutputEvent32Time",
            Level = 3,
            Kind = Kind.Event,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 88,
            HasFlags = true,
            HasTime = true,
            ValueBits = 32,
        },
        [GroupVar.GV(42, 4)] = new Descriptor
        {
            GV = GroupVar.GV(42, 4),
            Name = "AnalogOutputEvent16Time",
            Level = 3,
            Kind = Kind.Event,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 72,
            HasFlags = true,
            HasTime = true,
            ValueBits = 16,
        },
        [GroupVar.GV(42, 5)] = new Descriptor
        {
            GV = GroupVar.GV(42, 5),
            Name = "AnalogOutputEventFloat",
            Level = 3,
            Kind = Kind.Event,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 40,
            HasFlags = true,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(42, 6)] = new Descriptor
        {
            GV = GroupVar.GV(42, 6),
            Name = "AnalogOutputEventDouble",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 72,
            HasFlags = true,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(42, 7)] = new Descriptor
        {
            GV = GroupVar.GV(42, 7),
            Name = "AnalogOutputEventFloatTime",
            Level = 3,
            Kind = Kind.Event,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 88,
            HasFlags = true,
            HasTime = true,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(42, 8)] = new Descriptor
        {
            GV = GroupVar.GV(42, 8),
            Name = "AnalogOutputEventDoubleTime",
            Level = 4,
            Kind = Kind.Event,
            Measurement = PointType.AnalogOutputStatus,
            SizeBits = 120,
            HasFlags = true,
            HasTime = true,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(43, 1)] = new Descriptor
        {
            GV = GroupVar.GV(43, 1),
            Name = "AnalogOutputCmdEvent32",
            Level = 4,
            Kind = Kind.CommandEvent,
            Measurement = PointType.Unknown,
            SizeBits = 40,
            ValueBits = 32,
        },
        [GroupVar.GV(43, 2)] = new Descriptor
        {
            GV = GroupVar.GV(43, 2),
            Name = "AnalogOutputCmdEvent16",
            Level = 4,
            Kind = Kind.CommandEvent,
            Measurement = PointType.Unknown,
            SizeBits = 24,
            ValueBits = 16,
        },
        [GroupVar.GV(43, 3)] = new Descriptor
        {
            GV = GroupVar.GV(43, 3),
            Name = "AnalogOutputCmdEvent32Time",
            Level = 4,
            Kind = Kind.CommandEvent,
            Measurement = PointType.Unknown,
            SizeBits = 88,
            HasTime = true,
            ValueBits = 32,
        },
        [GroupVar.GV(43, 4)] = new Descriptor
        {
            GV = GroupVar.GV(43, 4),
            Name = "AnalogOutputCmdEvent16Time",
            Level = 4,
            Kind = Kind.CommandEvent,
            Measurement = PointType.Unknown,
            SizeBits = 72,
            HasTime = true,
            ValueBits = 16,
        },
        [GroupVar.GV(43, 5)] = new Descriptor
        {
            GV = GroupVar.GV(43, 5),
            Name = "AnalogOutputCmdEventFloat",
            Level = 4,
            Kind = Kind.CommandEvent,
            Measurement = PointType.Unknown,
            SizeBits = 40,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(43, 6)] = new Descriptor
        {
            GV = GroupVar.GV(43, 6),
            Name = "AnalogOutputCmdEventDouble",
            Level = 4,
            Kind = Kind.CommandEvent,
            Measurement = PointType.Unknown,
            SizeBits = 72,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(43, 7)] = new Descriptor
        {
            GV = GroupVar.GV(43, 7),
            Name = "AnalogOutputCmdEventFloatTime",
            Level = 4,
            Kind = Kind.CommandEvent,
            Measurement = PointType.Unknown,
            SizeBits = 88,
            HasTime = true,
            ValueBits = 32,
            FloatValue = true,
        },
        [GroupVar.GV(43, 8)] = new Descriptor
        {
            GV = GroupVar.GV(43, 8),
            Name = "AnalogOutputCmdEventDoubleTime",
            Level = 4,
            Kind = Kind.CommandEvent,
            Measurement = PointType.Unknown,
            SizeBits = 120,
            HasTime = true,
            ValueBits = 64,
            FloatValue = true,
        },
        [GroupVar.GV(50, 1)] = new Descriptor
        {
            GV = GroupVar.GV(50, 1),
            Name = "TimeAndDate",
            Level = 1,
            Kind = Kind.Time,
            Measurement = PointType.Unknown,
            SizeBits = 48,
            HasTime = true,
        },
        [GroupVar.GV(50, 2)] = new Descriptor
        {
            GV = GroupVar.GV(50, 2),
            Name = "TimeAndDateInterval",
            Level = 4,
            Kind = Kind.Time,
            Measurement = PointType.Unknown,
            SizeBits = 80,
            HasTime = true,
        },
        [GroupVar.GV(50, 3)] = new Descriptor
        {
            GV = GroupVar.GV(50, 3),
            Name = "TimeAndDateLastRecorded",
            Level = 3,
            Kind = Kind.Time,
            Measurement = PointType.Unknown,
            SizeBits = 48,
            HasTime = true,
        },
        [GroupVar.GV(50, 4)] = new Descriptor
        {
            GV = GroupVar.GV(50, 4),
            Name = "TimeAndDateIndexed",
            Level = 4,
            Kind = Kind.Time,
            Measurement = PointType.Unknown,
            SizeBits = 88,
            HasTime = true,
        },
        [GroupVar.GV(51, 1)] = new Descriptor
        {
            GV = GroupVar.GV(51, 1),
            Name = "TimeAndDateCTO",
            Level = 2,
            Kind = Kind.Time,
            Measurement = PointType.Unknown,
            SizeBits = 48,
            HasTime = true,
        },
        [GroupVar.GV(51, 2)] = new Descriptor
        {
            GV = GroupVar.GV(51, 2),
            Name = "UnsyncTimeAndDateCTO",
            Level = 2,
            Kind = Kind.Time,
            Measurement = PointType.Unknown,
            SizeBits = 48,
            HasTime = true,
        },
        [GroupVar.GV(52, 1)] = new Descriptor
        {
            GV = GroupVar.GV(52, 1),
            Name = "TimeDelayCoarse",
            Level = 1,
            Kind = Kind.Time,
            Measurement = PointType.Unknown,
            SizeBits = 16,
            ValueBits = 16,
        },
        [GroupVar.GV(52, 2)] = new Descriptor
        {
            GV = GroupVar.GV(52, 2),
            Name = "TimeDelayFine",
            Level = 1,
            Kind = Kind.Time,
            Measurement = PointType.Unknown,
            SizeBits = 16,
            ValueBits = 16,
        },
        [GroupVar.GV(60, 1)] = new Descriptor
        {
            GV = GroupVar.GV(60, 1),
            Name = "Class0Data",
            Level = 1,
            Kind = Kind.Class,
            Measurement = PointType.Unknown,
            SizeBits = 0,
        },
        [GroupVar.GV(60, 2)] = new Descriptor
        {
            GV = GroupVar.GV(60, 2),
            Name = "Class1Data",
            Level = 1,
            Kind = Kind.Class,
            Measurement = PointType.Unknown,
            SizeBits = 0,
        },
        [GroupVar.GV(60, 3)] = new Descriptor
        {
            GV = GroupVar.GV(60, 3),
            Name = "Class2Data",
            Level = 1,
            Kind = Kind.Class,
            Measurement = PointType.Unknown,
            SizeBits = 0,
        },
        [GroupVar.GV(60, 4)] = new Descriptor
        {
            GV = GroupVar.GV(60, 4),
            Name = "Class3Data",
            Level = 1,
            Kind = Kind.Class,
            Measurement = PointType.Unknown,
            SizeBits = 0,
        },
        [GroupVar.GV(80, 1)] = new Descriptor
        {
            GV = GroupVar.GV(80, 1),
            Name = "InternalIndications",
            Level = 1,
            Kind = Kind.Indication,
            Measurement = PointType.Unknown,
            SizeBits = 1,
            Packed = true,
        },
    };

    /// <summary>
    /// Groups that carry their octet length in the variation number, so a
    /// range of them needs no size table entry.
    /// </summary>
    private static readonly HashSet<byte> LengthIsVariationGroups =
    [
        110, // OctetString
        111, // OctetStringEvent
        112, // VirtualTerminalOutput
        113, // VirtualTerminalEvent
    ];

    /// <summary>
    /// Groups that are genuinely variable-length. Their encodings carry an
    /// explicit size, so a parser walks them instead of looking them up.
    /// </summary>
    private static readonly HashSet<byte> VariableGroups =
    [
        0, // DeviceAttribute
        70, // FileTransfer
    ];
}
