// <auto-generated>
// Code generated by build/SharpDnp3.Generator from
// src/SharpDnp3/Objects/Spec/dnp3_objects.yaml. DO NOT EDIT.
// </auto-generated>
//
// SharpDnp3 — a DNP3 (IEEE 1815-2012) implementation in C#.
// Copyright (C) 2026 Ricardo Olsen / DSC Systems
// Licensed under the GNU General Public License v3.0 or later.

using System.Buffers.Binary;

namespace SharpDnp3.Objects;

public static partial class ObjectRegistry
{
    // ---- Binary ----

    /// <summary>Decodes g1v2, BinaryInputWithFlags.</summary>
    private static Binary ParseG1V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Binary((buf[0] & 0x80) != 0, flags, time);
    }

    /// <summary>Encodes g1v2, BinaryInputWithFlags.</summary>
    private static void WriteG1V2(List<byte> dst, Binary v, Context ctx)
    {
        var flags = v.Flags.Clear(Flags.StateBit);
        if (v.Value)
        {
            flags = flags.Set(Flags.StateBit);
        }

        dst.Add(flags.Value);

        _ = ctx;
    }

    /// <summary>Decodes g2v1, BinaryInputEventNoTime.</summary>
    private static Binary ParseG2V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Binary((buf[0] & 0x80) != 0, flags, time);
    }

    /// <summary>Encodes g2v1, BinaryInputEventNoTime.</summary>
    private static void WriteG2V1(List<byte> dst, Binary v, Context ctx)
    {
        var flags = v.Flags.Clear(Flags.StateBit);
        if (v.Value)
        {
            flags = flags.Set(Flags.StateBit);
        }

        dst.Add(flags.Value);

        _ = ctx;
    }

    /// <summary>Decodes g2v2, BinaryInputEventAbsTime.</summary>
    private static Binary ParseG2V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(1, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Binary((buf[0] & 0x80) != 0, flags, time);
    }

    /// <summary>Encodes g2v2, BinaryInputEventAbsTime.</summary>
    private static void WriteG2V2(List<byte> dst, Binary v, Context ctx)
    {
        var flags = v.Flags.Clear(Flags.StateBit);
        if (v.Value)
        {
            flags = flags.Set(Flags.StateBit);
        }

        dst.Add(flags.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g2v3, BinaryInputEventRelTime.</summary>
    private static Binary ParseG2V3(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        // A relative-time event is an offset from the common time of
        // occurrence in a preceding group 51 object. Without one the
        // offset is meaningless, so the timestamp is left invalid
        // rather than being anchored to the epoch.
        var time = ctx.RelativeTime(BinaryPrimitives.ReadUInt16LittleEndian(buf.Slice(1, 2)));
        return new Binary((buf[0] & 0x80) != 0, flags, time);
    }

    /// <summary>Encodes g2v3, BinaryInputEventRelTime.</summary>
    private static void WriteG2V3(List<byte> dst, Binary v, Context ctx)
    {
        var flags = v.Flags.Clear(Flags.StateBit);
        if (v.Value)
        {
            flags = flags.Set(Flags.StateBit);
        }

        dst.Add(flags.Value);
        ObjectConvert.AppendUInt16(dst, ctx.RelativeOffset(v.Time));
    }

    private static readonly Dictionary<GroupVar, Codec<Binary>> BinaryCodecs = new()
    {
        [GroupVar.GV(1, 2)] = new Codec<Binary>(ParseG1V2, WriteG1V2),
        [GroupVar.GV(2, 1)] = new Codec<Binary>(ParseG2V1, WriteG2V1),
        [GroupVar.GV(2, 2)] = new Codec<Binary>(ParseG2V2, WriteG2V2),
        [GroupVar.GV(2, 3)] = new Codec<Binary>(ParseG2V3, WriteG2V3),
    };

    // ---- DoubleBitBinary ----

    /// <summary>Decodes g3v2, DoubleBitInputWithFlags.</summary>
    private static DoubleBitBinary ParseG3V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new DoubleBitBinary((DoubleBit)(buf[0] >> 6), flags, time);
    }

    /// <summary>Encodes g3v2, DoubleBitInputWithFlags.</summary>
    private static void WriteG3V2(List<byte> dst, DoubleBitBinary v, Context ctx)
    {
        dst.Add((byte)((v.Flags.Value & 0x3F) | (((int)v.Value & 0x03) << 6)));

        _ = ctx;
    }

    /// <summary>Decodes g4v1, DoubleBitEventNoTime.</summary>
    private static DoubleBitBinary ParseG4V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new DoubleBitBinary((DoubleBit)(buf[0] >> 6), flags, time);
    }

    /// <summary>Encodes g4v1, DoubleBitEventNoTime.</summary>
    private static void WriteG4V1(List<byte> dst, DoubleBitBinary v, Context ctx)
    {
        dst.Add((byte)((v.Flags.Value & 0x3F) | (((int)v.Value & 0x03) << 6)));

        _ = ctx;
    }

    /// <summary>Decodes g4v2, DoubleBitEventAbsTime.</summary>
    private static DoubleBitBinary ParseG4V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(1, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new DoubleBitBinary((DoubleBit)(buf[0] >> 6), flags, time);
    }

    /// <summary>Encodes g4v2, DoubleBitEventAbsTime.</summary>
    private static void WriteG4V2(List<byte> dst, DoubleBitBinary v, Context ctx)
    {
        dst.Add((byte)((v.Flags.Value & 0x3F) | (((int)v.Value & 0x03) << 6)));
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g4v3, DoubleBitEventRelTime.</summary>
    private static DoubleBitBinary ParseG4V3(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        // A relative-time event is an offset from the common time of
        // occurrence in a preceding group 51 object. Without one the
        // offset is meaningless, so the timestamp is left invalid
        // rather than being anchored to the epoch.
        var time = ctx.RelativeTime(BinaryPrimitives.ReadUInt16LittleEndian(buf.Slice(1, 2)));
        return new DoubleBitBinary((DoubleBit)(buf[0] >> 6), flags, time);
    }

    /// <summary>Encodes g4v3, DoubleBitEventRelTime.</summary>
    private static void WriteG4V3(List<byte> dst, DoubleBitBinary v, Context ctx)
    {
        dst.Add((byte)((v.Flags.Value & 0x3F) | (((int)v.Value & 0x03) << 6)));
        ObjectConvert.AppendUInt16(dst, ctx.RelativeOffset(v.Time));
    }

    private static readonly Dictionary<GroupVar, Codec<DoubleBitBinary>> DoubleBitCodecs = new()
    {
        [GroupVar.GV(3, 2)] = new Codec<DoubleBitBinary>(ParseG3V2, WriteG3V2),
        [GroupVar.GV(4, 1)] = new Codec<DoubleBitBinary>(ParseG4V1, WriteG4V1),
        [GroupVar.GV(4, 2)] = new Codec<DoubleBitBinary>(ParseG4V2, WriteG4V2),
        [GroupVar.GV(4, 3)] = new Codec<DoubleBitBinary>(ParseG4V3, WriteG4V3),
    };

    // ---- Counter ----

    /// <summary>Decodes g20v1, Counter32WithFlag.</summary>
    private static Counter ParseG20V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Counter(BinaryPrimitives.ReadUInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g20v1, Counter32WithFlag.</summary>
    private static void WriteG20V1(List<byte> dst, Counter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt32(dst, (uint)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g20v2, Counter16WithFlag.</summary>
    private static Counter ParseG20V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Counter((uint)BinaryPrimitives.ReadUInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g20v2, Counter16WithFlag.</summary>
    private static void WriteG20V2(List<byte> dst, Counter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt16(dst, (ushort)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g20v5, Counter32NoFlag.</summary>
    private static Counter ParseG20V5(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = Flags.Online;
        var time = Timestamp.NoTime();
        return new Counter(BinaryPrimitives.ReadUInt32LittleEndian(buf.Slice(0, 4)), flags, time);
    }

    /// <summary>Encodes g20v5, Counter32NoFlag.</summary>
    private static void WriteG20V5(List<byte> dst, Counter v, Context ctx)
    {
        ObjectConvert.AppendUInt32(dst, (uint)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g20v6, Counter16NoFlag.</summary>
    private static Counter ParseG20V6(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = Flags.Online;
        var time = Timestamp.NoTime();
        return new Counter((uint)BinaryPrimitives.ReadUInt16LittleEndian(buf.Slice(0, 2)), flags, time);
    }

    /// <summary>Encodes g20v6, Counter16NoFlag.</summary>
    private static void WriteG20V6(List<byte> dst, Counter v, Context ctx)
    {
        ObjectConvert.AppendUInt16(dst, (ushort)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g22v1, CounterEvent32WithFlag.</summary>
    private static Counter ParseG22V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Counter(BinaryPrimitives.ReadUInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g22v1, CounterEvent32WithFlag.</summary>
    private static void WriteG22V1(List<byte> dst, Counter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt32(dst, (uint)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g22v2, CounterEvent16WithFlag.</summary>
    private static Counter ParseG22V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Counter((uint)BinaryPrimitives.ReadUInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g22v2, CounterEvent16WithFlag.</summary>
    private static void WriteG22V2(List<byte> dst, Counter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt16(dst, (ushort)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g22v5, CounterEvent32WithFlagTime.</summary>
    private static Counter ParseG22V5(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(5, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Counter(BinaryPrimitives.ReadUInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g22v5, CounterEvent32WithFlagTime.</summary>
    private static void WriteG22V5(List<byte> dst, Counter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt32(dst, (uint)v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g22v6, CounterEvent16WithFlagTime.</summary>
    private static Counter ParseG22V6(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(3, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Counter((uint)BinaryPrimitives.ReadUInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g22v6, CounterEvent16WithFlagTime.</summary>
    private static void WriteG22V6(List<byte> dst, Counter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt16(dst, (ushort)v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    private static readonly Dictionary<GroupVar, Codec<Counter>> CounterCodecs = new()
    {
        [GroupVar.GV(20, 1)] = new Codec<Counter>(ParseG20V1, WriteG20V1),
        [GroupVar.GV(20, 2)] = new Codec<Counter>(ParseG20V2, WriteG20V2),
        [GroupVar.GV(20, 5)] = new Codec<Counter>(ParseG20V5, WriteG20V5),
        [GroupVar.GV(20, 6)] = new Codec<Counter>(ParseG20V6, WriteG20V6),
        [GroupVar.GV(22, 1)] = new Codec<Counter>(ParseG22V1, WriteG22V1),
        [GroupVar.GV(22, 2)] = new Codec<Counter>(ParseG22V2, WriteG22V2),
        [GroupVar.GV(22, 5)] = new Codec<Counter>(ParseG22V5, WriteG22V5),
        [GroupVar.GV(22, 6)] = new Codec<Counter>(ParseG22V6, WriteG22V6),
    };

    // ---- FrozenCounter ----

    /// <summary>Decodes g21v1, FrozenCounter32WithFlag.</summary>
    private static FrozenCounter ParseG21V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new FrozenCounter(BinaryPrimitives.ReadUInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g21v1, FrozenCounter32WithFlag.</summary>
    private static void WriteG21V1(List<byte> dst, FrozenCounter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt32(dst, (uint)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g21v2, FrozenCounter16WithFlag.</summary>
    private static FrozenCounter ParseG21V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new FrozenCounter((uint)BinaryPrimitives.ReadUInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g21v2, FrozenCounter16WithFlag.</summary>
    private static void WriteG21V2(List<byte> dst, FrozenCounter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt16(dst, (ushort)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g21v5, FrozenCounter32WithFlagTime.</summary>
    private static FrozenCounter ParseG21V5(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(5, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new FrozenCounter(BinaryPrimitives.ReadUInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g21v5, FrozenCounter32WithFlagTime.</summary>
    private static void WriteG21V5(List<byte> dst, FrozenCounter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt32(dst, (uint)v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g21v6, FrozenCounter16WithFlagTime.</summary>
    private static FrozenCounter ParseG21V6(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(3, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new FrozenCounter((uint)BinaryPrimitives.ReadUInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g21v6, FrozenCounter16WithFlagTime.</summary>
    private static void WriteG21V6(List<byte> dst, FrozenCounter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt16(dst, (ushort)v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g21v9, FrozenCounter32NoFlag.</summary>
    private static FrozenCounter ParseG21V9(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = Flags.Online;
        var time = Timestamp.NoTime();
        return new FrozenCounter(BinaryPrimitives.ReadUInt32LittleEndian(buf.Slice(0, 4)), flags, time);
    }

    /// <summary>Encodes g21v9, FrozenCounter32NoFlag.</summary>
    private static void WriteG21V9(List<byte> dst, FrozenCounter v, Context ctx)
    {
        ObjectConvert.AppendUInt32(dst, (uint)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g21v10, FrozenCounter16NoFlag.</summary>
    private static FrozenCounter ParseG21V10(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = Flags.Online;
        var time = Timestamp.NoTime();
        return new FrozenCounter((uint)BinaryPrimitives.ReadUInt16LittleEndian(buf.Slice(0, 2)), flags, time);
    }

    /// <summary>Encodes g21v10, FrozenCounter16NoFlag.</summary>
    private static void WriteG21V10(List<byte> dst, FrozenCounter v, Context ctx)
    {
        ObjectConvert.AppendUInt16(dst, (ushort)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g23v1, FrozenCounterEvent32WithFlag.</summary>
    private static FrozenCounter ParseG23V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new FrozenCounter(BinaryPrimitives.ReadUInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g23v1, FrozenCounterEvent32WithFlag.</summary>
    private static void WriteG23V1(List<byte> dst, FrozenCounter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt32(dst, (uint)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g23v2, FrozenCounterEvent16WithFlag.</summary>
    private static FrozenCounter ParseG23V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new FrozenCounter((uint)BinaryPrimitives.ReadUInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g23v2, FrozenCounterEvent16WithFlag.</summary>
    private static void WriteG23V2(List<byte> dst, FrozenCounter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt16(dst, (ushort)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g23v5, FrozenCounterEvent32WithFlagTime.</summary>
    private static FrozenCounter ParseG23V5(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(5, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new FrozenCounter(BinaryPrimitives.ReadUInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g23v5, FrozenCounterEvent32WithFlagTime.</summary>
    private static void WriteG23V5(List<byte> dst, FrozenCounter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt32(dst, (uint)v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g23v6, FrozenCounterEvent16WithFlagTime.</summary>
    private static FrozenCounter ParseG23V6(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(3, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new FrozenCounter((uint)BinaryPrimitives.ReadUInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g23v6, FrozenCounterEvent16WithFlagTime.</summary>
    private static void WriteG23V6(List<byte> dst, FrozenCounter v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendUInt16(dst, (ushort)v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    private static readonly Dictionary<GroupVar, Codec<FrozenCounter>> FrozenCounterCodecs = new()
    {
        [GroupVar.GV(21, 1)] = new Codec<FrozenCounter>(ParseG21V1, WriteG21V1),
        [GroupVar.GV(21, 2)] = new Codec<FrozenCounter>(ParseG21V2, WriteG21V2),
        [GroupVar.GV(21, 5)] = new Codec<FrozenCounter>(ParseG21V5, WriteG21V5),
        [GroupVar.GV(21, 6)] = new Codec<FrozenCounter>(ParseG21V6, WriteG21V6),
        [GroupVar.GV(21, 9)] = new Codec<FrozenCounter>(ParseG21V9, WriteG21V9),
        [GroupVar.GV(21, 10)] = new Codec<FrozenCounter>(ParseG21V10, WriteG21V10),
        [GroupVar.GV(23, 1)] = new Codec<FrozenCounter>(ParseG23V1, WriteG23V1),
        [GroupVar.GV(23, 2)] = new Codec<FrozenCounter>(ParseG23V2, WriteG23V2),
        [GroupVar.GV(23, 5)] = new Codec<FrozenCounter>(ParseG23V5, WriteG23V5),
        [GroupVar.GV(23, 6)] = new Codec<FrozenCounter>(ParseG23V6, WriteG23V6),
    };

    // ---- Analog ----

    /// <summary>Decodes g30v1, AnalogInput32WithFlag.</summary>
    private static Analog ParseG30V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g30v1, AnalogInput32WithFlag.</summary>
    private static void WriteG30V1(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g30v2, AnalogInput16WithFlag.</summary>
    private static Analog ParseG30V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g30v2, AnalogInput16WithFlag.</summary>
    private static void WriteG30V2(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g30v3, AnalogInput32NoFlag.</summary>
    private static Analog ParseG30V3(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = Flags.Online;
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(0, 4)), flags, time);
    }

    /// <summary>Encodes g30v3, AnalogInput32NoFlag.</summary>
    private static void WriteG30V3(List<byte> dst, Analog v, Context ctx)
    {
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g30v4, AnalogInput16NoFlag.</summary>
    private static Analog ParseG30V4(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = Flags.Online;
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(0, 2)), flags, time);
    }

    /// <summary>Encodes g30v4, AnalogInput16NoFlag.</summary>
    private static void WriteG30V4(List<byte> dst, Analog v, Context ctx)
    {
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g30v5, AnalogInputFloatWithFlag.</summary>
    private static Analog ParseG30V5(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadSingleLittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g30v5, AnalogInputFloatWithFlag.</summary>
    private static void WriteG30V5(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendSingle(dst, (float)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g30v6, AnalogInputDoubleWithFlag.</summary>
    private static Analog ParseG30V6(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog(BinaryPrimitives.ReadDoubleLittleEndian(buf.Slice(1, 8)), flags, time);
    }

    /// <summary>Encodes g30v6, AnalogInputDoubleWithFlag.</summary>
    private static void WriteG30V6(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendDouble(dst, v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g31v1, FrozenAnalog32WithFlag.</summary>
    private static Analog ParseG31V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g31v1, FrozenAnalog32WithFlag.</summary>
    private static void WriteG31V1(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g31v2, FrozenAnalog16WithFlag.</summary>
    private static Analog ParseG31V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g31v2, FrozenAnalog16WithFlag.</summary>
    private static void WriteG31V2(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g31v3, FrozenAnalog32WithFlagTime.</summary>
    private static Analog ParseG31V3(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(5, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Analog((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g31v3, FrozenAnalog32WithFlagTime.</summary>
    private static void WriteG31V3(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g31v4, FrozenAnalog16WithFlagTime.</summary>
    private static Analog ParseG31V4(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(3, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Analog((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g31v4, FrozenAnalog16WithFlagTime.</summary>
    private static void WriteG31V4(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g31v5, FrozenAnalog32NoFlag.</summary>
    private static Analog ParseG31V5(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = Flags.Online;
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(0, 4)), flags, time);
    }

    /// <summary>Encodes g31v5, FrozenAnalog32NoFlag.</summary>
    private static void WriteG31V5(List<byte> dst, Analog v, Context ctx)
    {
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g31v6, FrozenAnalog16NoFlag.</summary>
    private static Analog ParseG31V6(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = Flags.Online;
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(0, 2)), flags, time);
    }

    /// <summary>Encodes g31v6, FrozenAnalog16NoFlag.</summary>
    private static void WriteG31V6(List<byte> dst, Analog v, Context ctx)
    {
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g31v7, FrozenAnalogFloatWithFlag.</summary>
    private static Analog ParseG31V7(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadSingleLittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g31v7, FrozenAnalogFloatWithFlag.</summary>
    private static void WriteG31V7(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendSingle(dst, (float)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g31v8, FrozenAnalogDoubleWithFlag.</summary>
    private static Analog ParseG31V8(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog(BinaryPrimitives.ReadDoubleLittleEndian(buf.Slice(1, 8)), flags, time);
    }

    /// <summary>Encodes g31v8, FrozenAnalogDoubleWithFlag.</summary>
    private static void WriteG31V8(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendDouble(dst, v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g32v1, AnalogEvent32WithFlag.</summary>
    private static Analog ParseG32V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g32v1, AnalogEvent32WithFlag.</summary>
    private static void WriteG32V1(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g32v2, AnalogEvent16WithFlag.</summary>
    private static Analog ParseG32V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g32v2, AnalogEvent16WithFlag.</summary>
    private static void WriteG32V2(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g32v3, AnalogEvent32WithFlagTime.</summary>
    private static Analog ParseG32V3(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(5, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Analog((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g32v3, AnalogEvent32WithFlagTime.</summary>
    private static void WriteG32V3(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g32v4, AnalogEvent16WithFlagTime.</summary>
    private static Analog ParseG32V4(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(3, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Analog((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g32v4, AnalogEvent16WithFlagTime.</summary>
    private static void WriteG32V4(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g32v5, AnalogEventFloatWithFlag.</summary>
    private static Analog ParseG32V5(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadSingleLittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g32v5, AnalogEventFloatWithFlag.</summary>
    private static void WriteG32V5(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendSingle(dst, (float)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g32v6, AnalogEventDoubleWithFlag.</summary>
    private static Analog ParseG32V6(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog(BinaryPrimitives.ReadDoubleLittleEndian(buf.Slice(1, 8)), flags, time);
    }

    /// <summary>Encodes g32v6, AnalogEventDoubleWithFlag.</summary>
    private static void WriteG32V6(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendDouble(dst, v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g32v7, AnalogEventFloatWithFlagTime.</summary>
    private static Analog ParseG32V7(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(5, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Analog((double)BinaryPrimitives.ReadSingleLittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g32v7, AnalogEventFloatWithFlagTime.</summary>
    private static void WriteG32V7(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendSingle(dst, (float)v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g32v8, AnalogEventDoubleWithFlagTime.</summary>
    private static Analog ParseG32V8(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(9, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Analog(BinaryPrimitives.ReadDoubleLittleEndian(buf.Slice(1, 8)), flags, time);
    }

    /// <summary>Encodes g32v8, AnalogEventDoubleWithFlagTime.</summary>
    private static void WriteG32V8(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendDouble(dst, v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g33v1, FrozenAnalogEvent32WithFlag.</summary>
    private static Analog ParseG33V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g33v1, FrozenAnalogEvent32WithFlag.</summary>
    private static void WriteG33V1(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g33v2, FrozenAnalogEvent16WithFlag.</summary>
    private static Analog ParseG33V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g33v2, FrozenAnalogEvent16WithFlag.</summary>
    private static void WriteG33V2(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g33v3, FrozenAnalogEvent32WithFlagTime.</summary>
    private static Analog ParseG33V3(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(5, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Analog((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g33v3, FrozenAnalogEvent32WithFlagTime.</summary>
    private static void WriteG33V3(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g33v4, FrozenAnalogEvent16WithFlagTime.</summary>
    private static Analog ParseG33V4(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(3, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Analog((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g33v4, FrozenAnalogEvent16WithFlagTime.</summary>
    private static void WriteG33V4(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g33v5, FrozenAnalogEventFloatWithFlag.</summary>
    private static Analog ParseG33V5(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog((double)BinaryPrimitives.ReadSingleLittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g33v5, FrozenAnalogEventFloatWithFlag.</summary>
    private static void WriteG33V5(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendSingle(dst, (float)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g33v6, FrozenAnalogEventDoubleWithFlag.</summary>
    private static Analog ParseG33V6(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new Analog(BinaryPrimitives.ReadDoubleLittleEndian(buf.Slice(1, 8)), flags, time);
    }

    /// <summary>Encodes g33v6, FrozenAnalogEventDoubleWithFlag.</summary>
    private static void WriteG33V6(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendDouble(dst, v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g33v7, FrozenAnalogEventFloatWithFlagTime.</summary>
    private static Analog ParseG33V7(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(5, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Analog((double)BinaryPrimitives.ReadSingleLittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g33v7, FrozenAnalogEventFloatWithFlagTime.</summary>
    private static void WriteG33V7(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendSingle(dst, (float)v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g33v8, FrozenAnalogEventDoubleWithFlagTime.</summary>
    private static Analog ParseG33V8(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(9, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new Analog(BinaryPrimitives.ReadDoubleLittleEndian(buf.Slice(1, 8)), flags, time);
    }

    /// <summary>Encodes g33v8, FrozenAnalogEventDoubleWithFlagTime.</summary>
    private static void WriteG33V8(List<byte> dst, Analog v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendDouble(dst, v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    private static readonly Dictionary<GroupVar, Codec<Analog>> AnalogCodecs = new()
    {
        [GroupVar.GV(30, 1)] = new Codec<Analog>(ParseG30V1, WriteG30V1),
        [GroupVar.GV(30, 2)] = new Codec<Analog>(ParseG30V2, WriteG30V2),
        [GroupVar.GV(30, 3)] = new Codec<Analog>(ParseG30V3, WriteG30V3),
        [GroupVar.GV(30, 4)] = new Codec<Analog>(ParseG30V4, WriteG30V4),
        [GroupVar.GV(30, 5)] = new Codec<Analog>(ParseG30V5, WriteG30V5),
        [GroupVar.GV(30, 6)] = new Codec<Analog>(ParseG30V6, WriteG30V6),
        [GroupVar.GV(31, 1)] = new Codec<Analog>(ParseG31V1, WriteG31V1),
        [GroupVar.GV(31, 2)] = new Codec<Analog>(ParseG31V2, WriteG31V2),
        [GroupVar.GV(31, 3)] = new Codec<Analog>(ParseG31V3, WriteG31V3),
        [GroupVar.GV(31, 4)] = new Codec<Analog>(ParseG31V4, WriteG31V4),
        [GroupVar.GV(31, 5)] = new Codec<Analog>(ParseG31V5, WriteG31V5),
        [GroupVar.GV(31, 6)] = new Codec<Analog>(ParseG31V6, WriteG31V6),
        [GroupVar.GV(31, 7)] = new Codec<Analog>(ParseG31V7, WriteG31V7),
        [GroupVar.GV(31, 8)] = new Codec<Analog>(ParseG31V8, WriteG31V8),
        [GroupVar.GV(32, 1)] = new Codec<Analog>(ParseG32V1, WriteG32V1),
        [GroupVar.GV(32, 2)] = new Codec<Analog>(ParseG32V2, WriteG32V2),
        [GroupVar.GV(32, 3)] = new Codec<Analog>(ParseG32V3, WriteG32V3),
        [GroupVar.GV(32, 4)] = new Codec<Analog>(ParseG32V4, WriteG32V4),
        [GroupVar.GV(32, 5)] = new Codec<Analog>(ParseG32V5, WriteG32V5),
        [GroupVar.GV(32, 6)] = new Codec<Analog>(ParseG32V6, WriteG32V6),
        [GroupVar.GV(32, 7)] = new Codec<Analog>(ParseG32V7, WriteG32V7),
        [GroupVar.GV(32, 8)] = new Codec<Analog>(ParseG32V8, WriteG32V8),
        [GroupVar.GV(33, 1)] = new Codec<Analog>(ParseG33V1, WriteG33V1),
        [GroupVar.GV(33, 2)] = new Codec<Analog>(ParseG33V2, WriteG33V2),
        [GroupVar.GV(33, 3)] = new Codec<Analog>(ParseG33V3, WriteG33V3),
        [GroupVar.GV(33, 4)] = new Codec<Analog>(ParseG33V4, WriteG33V4),
        [GroupVar.GV(33, 5)] = new Codec<Analog>(ParseG33V5, WriteG33V5),
        [GroupVar.GV(33, 6)] = new Codec<Analog>(ParseG33V6, WriteG33V6),
        [GroupVar.GV(33, 7)] = new Codec<Analog>(ParseG33V7, WriteG33V7),
        [GroupVar.GV(33, 8)] = new Codec<Analog>(ParseG33V8, WriteG33V8),
    };

    // ---- BinaryOutputStatus ----

    /// <summary>Decodes g10v2, BinaryOutputWithFlags.</summary>
    private static BinaryOutputStatus ParseG10V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new BinaryOutputStatus((buf[0] & 0x80) != 0, flags, time);
    }

    /// <summary>Encodes g10v2, BinaryOutputWithFlags.</summary>
    private static void WriteG10V2(List<byte> dst, BinaryOutputStatus v, Context ctx)
    {
        var flags = v.Flags.Clear(Flags.StateBit);
        if (v.Value)
        {
            flags = flags.Set(Flags.StateBit);
        }

        dst.Add(flags.Value);

        _ = ctx;
    }

    /// <summary>Decodes g11v1, BinaryOutputEventNoTime.</summary>
    private static BinaryOutputStatus ParseG11V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new BinaryOutputStatus((buf[0] & 0x80) != 0, flags, time);
    }

    /// <summary>Encodes g11v1, BinaryOutputEventNoTime.</summary>
    private static void WriteG11V1(List<byte> dst, BinaryOutputStatus v, Context ctx)
    {
        var flags = v.Flags.Clear(Flags.StateBit);
        if (v.Value)
        {
            flags = flags.Set(Flags.StateBit);
        }

        dst.Add(flags.Value);

        _ = ctx;
    }

    /// <summary>Decodes g11v2, BinaryOutputEventAbsTime.</summary>
    private static BinaryOutputStatus ParseG11V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(1, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new BinaryOutputStatus((buf[0] & 0x80) != 0, flags, time);
    }

    /// <summary>Encodes g11v2, BinaryOutputEventAbsTime.</summary>
    private static void WriteG11V2(List<byte> dst, BinaryOutputStatus v, Context ctx)
    {
        var flags = v.Flags.Clear(Flags.StateBit);
        if (v.Value)
        {
            flags = flags.Set(Flags.StateBit);
        }

        dst.Add(flags.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    private static readonly Dictionary<GroupVar, Codec<BinaryOutputStatus>> BinaryOutputCodecs = new()
    {
        [GroupVar.GV(10, 2)] = new Codec<BinaryOutputStatus>(ParseG10V2, WriteG10V2),
        [GroupVar.GV(11, 1)] = new Codec<BinaryOutputStatus>(ParseG11V1, WriteG11V1),
        [GroupVar.GV(11, 2)] = new Codec<BinaryOutputStatus>(ParseG11V2, WriteG11V2),
    };

    // ---- AnalogOutputStatus ----

    /// <summary>Decodes g40v1, AnalogOutputStatus32.</summary>
    private static AnalogOutputStatus ParseG40V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new AnalogOutputStatus((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g40v1, AnalogOutputStatus32.</summary>
    private static void WriteG40V1(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g40v2, AnalogOutputStatus16.</summary>
    private static AnalogOutputStatus ParseG40V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new AnalogOutputStatus((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g40v2, AnalogOutputStatus16.</summary>
    private static void WriteG40V2(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g40v3, AnalogOutputStatusFloat.</summary>
    private static AnalogOutputStatus ParseG40V3(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new AnalogOutputStatus((double)BinaryPrimitives.ReadSingleLittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g40v3, AnalogOutputStatusFloat.</summary>
    private static void WriteG40V3(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendSingle(dst, (float)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g40v4, AnalogOutputStatusDouble.</summary>
    private static AnalogOutputStatus ParseG40V4(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new AnalogOutputStatus(BinaryPrimitives.ReadDoubleLittleEndian(buf.Slice(1, 8)), flags, time);
    }

    /// <summary>Encodes g40v4, AnalogOutputStatusDouble.</summary>
    private static void WriteG40V4(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendDouble(dst, v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g42v1, AnalogOutputEvent32.</summary>
    private static AnalogOutputStatus ParseG42V1(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new AnalogOutputStatus((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g42v1, AnalogOutputEvent32.</summary>
    private static void WriteG42V1(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g42v2, AnalogOutputEvent16.</summary>
    private static AnalogOutputStatus ParseG42V2(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new AnalogOutputStatus((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g42v2, AnalogOutputEvent16.</summary>
    private static void WriteG42V2(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));

        _ = ctx;
    }

    /// <summary>Decodes g42v3, AnalogOutputEvent32Time.</summary>
    private static AnalogOutputStatus ParseG42V3(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(5, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new AnalogOutputStatus((double)BinaryPrimitives.ReadInt32LittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g42v3, AnalogOutputEvent32Time.</summary>
    private static void WriteG42V3(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt32(dst, ObjectConvert.ClampInt32(v.Value));
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g42v4, AnalogOutputEvent16Time.</summary>
    private static AnalogOutputStatus ParseG42V4(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(3, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new AnalogOutputStatus((double)BinaryPrimitives.ReadInt16LittleEndian(buf.Slice(1, 2)), flags, time);
    }

    /// <summary>Encodes g42v4, AnalogOutputEvent16Time.</summary>
    private static void WriteG42V4(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendInt16(dst, ObjectConvert.ClampInt16(v.Value));
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g42v5, AnalogOutputEventFloat.</summary>
    private static AnalogOutputStatus ParseG42V5(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new AnalogOutputStatus((double)BinaryPrimitives.ReadSingleLittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g42v5, AnalogOutputEventFloat.</summary>
    private static void WriteG42V5(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendSingle(dst, (float)v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g42v6, AnalogOutputEventDouble.</summary>
    private static AnalogOutputStatus ParseG42V6(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = Timestamp.NoTime();
        return new AnalogOutputStatus(BinaryPrimitives.ReadDoubleLittleEndian(buf.Slice(1, 8)), flags, time);
    }

    /// <summary>Encodes g42v6, AnalogOutputEventDouble.</summary>
    private static void WriteG42V6(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendDouble(dst, v.Value);

        _ = ctx;
    }

    /// <summary>Decodes g42v7, AnalogOutputEventFloatTime.</summary>
    private static AnalogOutputStatus ParseG42V7(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(5, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new AnalogOutputStatus((double)BinaryPrimitives.ReadSingleLittleEndian(buf.Slice(1, 4)), flags, time);
    }

    /// <summary>Encodes g42v7, AnalogOutputEventFloatTime.</summary>
    private static void WriteG42V7(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendSingle(dst, (float)v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    /// <summary>Decodes g42v8, AnalogOutputEventDoubleTime.</summary>
    private static AnalogOutputStatus ParseG42V8(ReadOnlySpan<byte> buf, Context ctx)
    {
        var flags = new Flags(buf[0]);
        var time = new Timestamp
        {
            Time = Dnp3Time.FromDnp3(ObjectConvert.ReadTime48(buf.Slice(9, 6))),
            Quality = ctx.TimeQuality(),
        };
        return new AnalogOutputStatus(BinaryPrimitives.ReadDoubleLittleEndian(buf.Slice(1, 8)), flags, time);
    }

    /// <summary>Encodes g42v8, AnalogOutputEventDoubleTime.</summary>
    private static void WriteG42V8(List<byte> dst, AnalogOutputStatus v, Context ctx)
    {
        dst.Add(v.Flags.Value);
        ObjectConvert.AppendDouble(dst, v.Value);
        ObjectConvert.AppendTime48(dst, Dnp3Time.ToDnp3(v.Time.Time));

        _ = ctx;
    }

    private static readonly Dictionary<GroupVar, Codec<AnalogOutputStatus>> AnalogOutputCodecs = new()
    {
        [GroupVar.GV(40, 1)] = new Codec<AnalogOutputStatus>(ParseG40V1, WriteG40V1),
        [GroupVar.GV(40, 2)] = new Codec<AnalogOutputStatus>(ParseG40V2, WriteG40V2),
        [GroupVar.GV(40, 3)] = new Codec<AnalogOutputStatus>(ParseG40V3, WriteG40V3),
        [GroupVar.GV(40, 4)] = new Codec<AnalogOutputStatus>(ParseG40V4, WriteG40V4),
        [GroupVar.GV(42, 1)] = new Codec<AnalogOutputStatus>(ParseG42V1, WriteG42V1),
        [GroupVar.GV(42, 2)] = new Codec<AnalogOutputStatus>(ParseG42V2, WriteG42V2),
        [GroupVar.GV(42, 3)] = new Codec<AnalogOutputStatus>(ParseG42V3, WriteG42V3),
        [GroupVar.GV(42, 4)] = new Codec<AnalogOutputStatus>(ParseG42V4, WriteG42V4),
        [GroupVar.GV(42, 5)] = new Codec<AnalogOutputStatus>(ParseG42V5, WriteG42V5),
        [GroupVar.GV(42, 6)] = new Codec<AnalogOutputStatus>(ParseG42V6, WriteG42V6),
        [GroupVar.GV(42, 7)] = new Codec<AnalogOutputStatus>(ParseG42V7, WriteG42V7),
        [GroupVar.GV(42, 8)] = new Codec<AnalogOutputStatus>(ParseG42V8, WriteG42V8),
    };
}
