// <auto-generated>
// Code generated by build/SharpDnp3.Generator from
// src/SharpDnp3/Objects/Spec/dnp3_objects.yaml. DO NOT EDIT.
// </auto-generated>
//
// SharpDnp3 — a DNP3 (IEEE 1815-2012) implementation in C#.
// Copyright (C) 2026 Ricardo Olsen / DSC Systems
// Licensed under the GNU General Public License v3.0 or later.

namespace SharpDnp3.App;

internal static partial class ObjectSizing
{
    /// <summary>
    /// Maps a group and variation to the encoded size of one object in bits.
    /// Sizes under eight bits are bit-packed across a range.
    /// </summary>
    private static readonly Dictionary<ushort, int> GeneratedSizes = new()
    {
        [Gv(1, 1)] = 1, // BinaryInputPacked
        [Gv(1, 2)] = 8, // BinaryInputWithFlags
        [Gv(2, 1)] = 8, // BinaryInputEventNoTime
        [Gv(2, 2)] = 56, // BinaryInputEventAbsTime
        [Gv(2, 3)] = 24, // BinaryInputEventRelTime
        [Gv(3, 1)] = 2, // DoubleBitInputPacked
        [Gv(3, 2)] = 8, // DoubleBitInputWithFlags
        [Gv(4, 1)] = 8, // DoubleBitEventNoTime
        [Gv(4, 2)] = 56, // DoubleBitEventAbsTime
        [Gv(4, 3)] = 24, // DoubleBitEventRelTime
        [Gv(10, 1)] = 1, // BinaryOutputPacked
        [Gv(10, 2)] = 8, // BinaryOutputWithFlags
        [Gv(11, 1)] = 8, // BinaryOutputEventNoTime
        [Gv(11, 2)] = 56, // BinaryOutputEventAbsTime
        [Gv(12, 1)] = 88, // ControlRelayOutputBlock
        [Gv(12, 2)] = 88, // PatternControlBlock
        [Gv(12, 3)] = 1, // PatternMask
        [Gv(13, 1)] = 8, // BinaryOutputCmdEventNoTime
        [Gv(13, 2)] = 56, // BinaryOutputCmdEventAbsTime
        [Gv(20, 1)] = 40, // Counter32WithFlag
        [Gv(20, 2)] = 24, // Counter16WithFlag
        [Gv(20, 5)] = 32, // Counter32NoFlag
        [Gv(20, 6)] = 16, // Counter16NoFlag
        [Gv(21, 1)] = 40, // FrozenCounter32WithFlag
        [Gv(21, 2)] = 24, // FrozenCounter16WithFlag
        [Gv(21, 5)] = 88, // FrozenCounter32WithFlagTime
        [Gv(21, 6)] = 72, // FrozenCounter16WithFlagTime
        [Gv(21, 9)] = 32, // FrozenCounter32NoFlag
        [Gv(21, 10)] = 16, // FrozenCounter16NoFlag
        [Gv(22, 1)] = 40, // CounterEvent32WithFlag
        [Gv(22, 2)] = 24, // CounterEvent16WithFlag
        [Gv(22, 5)] = 88, // CounterEvent32WithFlagTime
        [Gv(22, 6)] = 72, // CounterEvent16WithFlagTime
        [Gv(23, 1)] = 40, // FrozenCounterEvent32WithFlag
        [Gv(23, 2)] = 24, // FrozenCounterEvent16WithFlag
        [Gv(23, 5)] = 88, // FrozenCounterEvent32WithFlagTime
        [Gv(23, 6)] = 72, // FrozenCounterEvent16WithFlagTime
        [Gv(30, 1)] = 40, // AnalogInput32WithFlag
        [Gv(30, 2)] = 24, // AnalogInput16WithFlag
        [Gv(30, 3)] = 32, // AnalogInput32NoFlag
        [Gv(30, 4)] = 16, // AnalogInput16NoFlag
        [Gv(30, 5)] = 40, // AnalogInputFloatWithFlag
        [Gv(30, 6)] = 72, // AnalogInputDoubleWithFlag
        [Gv(31, 1)] = 40, // FrozenAnalog32WithFlag
        [Gv(31, 2)] = 24, // FrozenAnalog16WithFlag
        [Gv(31, 3)] = 88, // FrozenAnalog32WithFlagTime
        [Gv(31, 4)] = 72, // FrozenAnalog16WithFlagTime
        [Gv(31, 5)] = 32, // FrozenAnalog32NoFlag
        [Gv(31, 6)] = 16, // FrozenAnalog16NoFlag
        [Gv(31, 7)] = 40, // FrozenAnalogFloatWithFlag
        [Gv(31, 8)] = 72, // FrozenAnalogDoubleWithFlag
        [Gv(32, 1)] = 40, // AnalogEvent32WithFlag
        [Gv(32, 2)] = 24, // AnalogEvent16WithFlag
        [Gv(32, 3)] = 88, // AnalogEvent32WithFlagTime
        [Gv(32, 4)] = 72, // AnalogEvent16WithFlagTime
        [Gv(32, 5)] = 40, // AnalogEventFloatWithFlag
        [Gv(32, 6)] = 72, // AnalogEventDoubleWithFlag
        [Gv(32, 7)] = 88, // AnalogEventFloatWithFlagTime
        [Gv(32, 8)] = 120, // AnalogEventDoubleWithFlagTime
        [Gv(33, 1)] = 40, // FrozenAnalogEvent32WithFlag
        [Gv(33, 2)] = 24, // FrozenAnalogEvent16WithFlag
        [Gv(33, 3)] = 88, // FrozenAnalogEvent32WithFlagTime
        [Gv(33, 4)] = 72, // FrozenAnalogEvent16WithFlagTime
        [Gv(33, 5)] = 40, // FrozenAnalogEventFloatWithFlag
        [Gv(33, 6)] = 72, // FrozenAnalogEventDoubleWithFlag
        [Gv(33, 7)] = 88, // FrozenAnalogEventFloatWithFlagTime
        [Gv(33, 8)] = 120, // FrozenAnalogEventDoubleWithFlagTime
        [Gv(34, 1)] = 16, // AnalogDeadband16
        [Gv(34, 2)] = 32, // AnalogDeadband32
        [Gv(34, 3)] = 32, // AnalogDeadbandFloat
        [Gv(40, 1)] = 40, // AnalogOutputStatus32
        [Gv(40, 2)] = 24, // AnalogOutputStatus16
        [Gv(40, 3)] = 40, // AnalogOutputStatusFloat
        [Gv(40, 4)] = 72, // AnalogOutputStatusDouble
        [Gv(41, 1)] = 40, // AnalogOutput32
        [Gv(41, 2)] = 24, // AnalogOutput16
        [Gv(41, 3)] = 40, // AnalogOutputFloat
        [Gv(41, 4)] = 72, // AnalogOutputDouble
        [Gv(42, 1)] = 40, // AnalogOutputEvent32
        [Gv(42, 2)] = 24, // AnalogOutputEvent16
        [Gv(42, 3)] = 88, // AnalogOutputEvent32Time
        [Gv(42, 4)] = 72, // AnalogOutputEvent16Time
        [Gv(42, 5)] = 40, // AnalogOutputEventFloat
        [Gv(42, 6)] = 72, // AnalogOutputEventDouble
        [Gv(42, 7)] = 88, // AnalogOutputEventFloatTime
        [Gv(42, 8)] = 120, // AnalogOutputEventDoubleTime
        [Gv(43, 1)] = 40, // AnalogOutputCmdEvent32
        [Gv(43, 2)] = 24, // AnalogOutputCmdEvent16
        [Gv(43, 3)] = 88, // AnalogOutputCmdEvent32Time
        [Gv(43, 4)] = 72, // AnalogOutputCmdEvent16Time
        [Gv(43, 5)] = 40, // AnalogOutputCmdEventFloat
        [Gv(43, 6)] = 72, // AnalogOutputCmdEventDouble
        [Gv(43, 7)] = 88, // AnalogOutputCmdEventFloatTime
        [Gv(43, 8)] = 120, // AnalogOutputCmdEventDoubleTime
        [Gv(50, 1)] = 48, // TimeAndDate
        [Gv(50, 2)] = 80, // TimeAndDateInterval
        [Gv(50, 3)] = 48, // TimeAndDateLastRecorded
        [Gv(50, 4)] = 88, // TimeAndDateIndexed
        [Gv(51, 1)] = 48, // TimeAndDateCTO
        [Gv(51, 2)] = 48, // UnsyncTimeAndDateCTO
        [Gv(52, 1)] = 16, // TimeDelayCoarse
        [Gv(52, 2)] = 16, // TimeDelayFine
        [Gv(60, 1)] = 0, // Class0Data
        [Gv(60, 2)] = 0, // Class1Data
        [Gv(60, 3)] = 0, // Class2Data
        [Gv(60, 4)] = 0, // Class3Data
        [Gv(80, 1)] = 1, // InternalIndications
    };

    /// <summary>
    /// Groups that carry their octet length in the variation number.
    /// </summary>
    private static readonly HashSet<byte> LengthIsVariationGroups =
    [
        110, // OctetString
        111, // OctetStringEvent
        112, // VirtualTerminalOutput
        113, // VirtualTerminalEvent
    ];

    /// <summary>
    /// Groups with no fixed size; their encoding carries one.
    /// </summary>
    private static readonly HashSet<byte> VariableGroups =
    [
        0, // DeviceAttribute
        70, // FileTransfer
    ];
}
