<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SharpDnp3.Tools.Explorer</RootNamespace>
    <AssemblyName>SharpDnp3.Tools.Explorer</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SharpDnp3/SharpDnp3.csproj" />
  </ItemGroup>

</Project>
